//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/bozydar/workspaces/sane/src/Sane/Sane.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Sane.Grammar {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class SaneLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, ID=11, ASTERISK=12, SLASH=13, PLUS=14, MINUS=15, NUMBER=16, WHITESPACE=17, 
		SingleLineComment=18, ESCAPED_STRING=19;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "ID", "ASTERISK", "SLASH", "PLUS", "MINUS", "NUMBER", "WHITESPACE", 
		"SingleLineComment", "ESCAPED_STRING", "LETTER", "DIGIT"
	};


	public SaneLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SaneLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'module'", "'end'", "'='", "'('", "')'", "'let'", "'in'", "'->'", 
		"':'", "','", null, "'*'", "'/'", "'+'", "'-'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, "ID", 
		"ASTERISK", "SLASH", "PLUS", "MINUS", "NUMBER", "WHITESPACE", "SingleLineComment", 
		"ESCAPED_STRING"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Sane.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SaneLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x15', '\x93', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\f', '\x6', '\f', 'N', '\n', '\f', '\r', '\f', '\xE', 
		'\f', 'O', '\x3', '\f', '\a', '\f', 'S', '\n', '\f', '\f', '\f', '\xE', 
		'\f', 'V', '\v', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x6', '\x11', '\x61', '\n', '\x11', '\r', '\x11', '\xE', '\x11', 
		'\x62', '\x3', '\x11', '\x3', '\x11', '\x6', '\x11', 'g', '\n', '\x11', 
		'\r', '\x11', '\xE', '\x11', 'h', '\x5', '\x11', 'k', '\n', '\x11', '\x3', 
		'\x12', '\x6', '\x12', 'n', '\n', '\x12', '\r', '\x12', '\xE', '\x12', 
		'o', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\a', '\x13', 'x', '\n', '\x13', '\f', '\x13', 
		'\xE', '\x13', '{', '\v', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\a', '\x14', '\x83', 
		'\n', '\x14', '\f', '\x14', '\xE', '\x14', '\x86', '\v', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x15', '\x6', '\x15', '\x8B', '\n', '\x15', 
		'\r', '\x15', '\xE', '\x15', '\x8C', '\x3', '\x16', '\x6', '\x16', '\x90', 
		'\n', '\x16', '\r', '\x16', '\xE', '\x16', '\x91', '\x2', '\x2', '\x17', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', 
		'\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', 
		'#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x2', '+', '\x2', '\x3', 
		'\x2', '\a', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x5', 
		'\x2', '\f', '\f', '\xF', '\xF', '\x202A', '\x202B', '\x3', '\x2', '$', 
		'$', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x3', '\x2', '\x32', ';', 
		'\x2', '\x9B', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '-', '\x3', '\x2', '\x2', '\x2', '\x5', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\a', '\x38', '\x3', '\x2', '\x2', '\x2', '\t', ':', '\x3', 
		'\x2', '\x2', '\x2', '\v', '<', '\x3', '\x2', '\x2', '\x2', '\r', '>', 
		'\x3', '\x2', '\x2', '\x2', '\xF', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\x45', '\x3', '\x2', '\x2', '\x2', '\x13', 'H', '\x3', '\x2', 
		'\x2', '\x2', '\x15', 'J', '\x3', '\x2', '\x2', '\x2', '\x17', 'M', '\x3', 
		'\x2', '\x2', '\x2', '\x19', 'W', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'Y', '\x3', '\x2', '\x2', '\x2', '\x1D', '[', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', ']', '\x3', '\x2', '\x2', '\x2', '!', '`', '\x3', '\x2', '\x2', 
		'\x2', '#', 'm', '\x3', '\x2', '\x2', '\x2', '%', 's', '\x3', '\x2', '\x2', 
		'\x2', '\'', '~', '\x3', '\x2', '\x2', '\x2', ')', '\x8A', '\x3', '\x2', 
		'\x2', '\x2', '+', '\x8F', '\x3', '\x2', '\x2', '\x2', '-', '.', '\a', 
		'o', '\x2', '\x2', '.', '/', '\a', 'q', '\x2', '\x2', '/', '\x30', '\a', 
		'\x66', '\x2', '\x2', '\x30', '\x31', '\a', 'w', '\x2', '\x2', '\x31', 
		'\x32', '\a', 'n', '\x2', '\x2', '\x32', '\x33', '\a', 'g', '\x2', '\x2', 
		'\x33', '\x4', '\x3', '\x2', '\x2', '\x2', '\x34', '\x35', '\a', 'g', 
		'\x2', '\x2', '\x35', '\x36', '\a', 'p', '\x2', '\x2', '\x36', '\x37', 
		'\a', '\x66', '\x2', '\x2', '\x37', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'\x38', '\x39', '\a', '?', '\x2', '\x2', '\x39', '\b', '\x3', '\x2', '\x2', 
		'\x2', ':', ';', '\a', '*', '\x2', '\x2', ';', '\n', '\x3', '\x2', '\x2', 
		'\x2', '<', '=', '\a', '+', '\x2', '\x2', '=', '\f', '\x3', '\x2', '\x2', 
		'\x2', '>', '?', '\a', 'n', '\x2', '\x2', '?', '@', '\a', 'g', '\x2', 
		'\x2', '@', '\x41', '\a', 'v', '\x2', '\x2', '\x41', '\xE', '\x3', '\x2', 
		'\x2', '\x2', '\x42', '\x43', '\a', 'k', '\x2', '\x2', '\x43', '\x44', 
		'\a', 'p', '\x2', '\x2', '\x44', '\x10', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x46', '\a', '/', '\x2', '\x2', '\x46', 'G', '\a', '@', '\x2', '\x2', 
		'G', '\x12', '\x3', '\x2', '\x2', '\x2', 'H', 'I', '\a', '<', '\x2', '\x2', 
		'I', '\x14', '\x3', '\x2', '\x2', '\x2', 'J', 'K', '\a', '.', '\x2', '\x2', 
		'K', '\x16', '\x3', '\x2', '\x2', '\x2', 'L', 'N', '\x5', ')', '\x15', 
		'\x2', 'M', 'L', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\x3', '\x2', '\x2', 
		'\x2', 'O', 'M', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\x3', '\x2', '\x2', 
		'\x2', 'P', 'T', '\x3', '\x2', '\x2', '\x2', 'Q', 'S', '\x5', '+', '\x16', 
		'\x2', 'R', 'Q', '\x3', '\x2', '\x2', '\x2', 'S', 'V', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'R', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\x3', '\x2', '\x2', 
		'\x2', 'U', '\x18', '\x3', '\x2', '\x2', '\x2', 'V', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'W', 'X', '\a', ',', '\x2', '\x2', 'X', '\x1A', '\x3', '\x2', 
		'\x2', '\x2', 'Y', 'Z', '\a', '\x31', '\x2', '\x2', 'Z', '\x1C', '\x3', 
		'\x2', '\x2', '\x2', '[', '\\', '\a', '-', '\x2', '\x2', '\\', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '/', '\x2', '\x2', '^', ' ', 
		'\x3', '\x2', '\x2', '\x2', '_', '\x61', '\x5', '+', '\x16', '\x2', '`', 
		'_', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '`', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x63', 'j', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x66', '\a', '\x30', '\x2', '\x2', '\x65', 'g', '\x5', '+', '\x16', '\x2', 
		'\x66', '\x65', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\x3', '\x2', '\x2', 
		'\x2', 'h', '\x66', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\x3', '\x2', 
		'\x2', '\x2', 'i', 'k', '\x3', '\x2', '\x2', '\x2', 'j', '\x64', '\x3', 
		'\x2', '\x2', '\x2', 'j', 'k', '\x3', '\x2', '\x2', '\x2', 'k', '\"', 
		'\x3', '\x2', '\x2', '\x2', 'l', 'n', '\t', '\x2', '\x2', '\x2', 'm', 
		'l', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', '\x2', '\x2', '\x2', 
		'o', 'm', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\x3', '\x2', '\x2', '\x2', 
		'p', 'q', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\b', '\x12', '\x2', '\x2', 
		'r', '$', '\x3', '\x2', '\x2', '\x2', 's', 't', '\a', '\x31', '\x2', '\x2', 
		't', 'u', '\a', '\x31', '\x2', '\x2', 'u', 'y', '\x3', '\x2', '\x2', '\x2', 
		'v', 'x', '\n', '\x3', '\x2', '\x2', 'w', 'v', '\x3', '\x2', '\x2', '\x2', 
		'x', '{', '\x3', '\x2', '\x2', '\x2', 'y', 'w', '\x3', '\x2', '\x2', '\x2', 
		'y', 'z', '\x3', '\x2', '\x2', '\x2', 'z', '|', '\x3', '\x2', '\x2', '\x2', 
		'{', 'y', '\x3', '\x2', '\x2', '\x2', '|', '}', '\b', '\x13', '\x3', '\x2', 
		'}', '&', '\x3', '\x2', '\x2', '\x2', '~', '\x84', '\a', '$', '\x2', '\x2', 
		'\x7F', '\x80', '\a', '$', '\x2', '\x2', '\x80', '\x83', '\a', '$', '\x2', 
		'\x2', '\x81', '\x83', '\n', '\x4', '\x2', '\x2', '\x82', '\x7F', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x81', '\x3', '\x2', '\x2', '\x2', '\x83', 
		'\x86', '\x3', '\x2', '\x2', '\x2', '\x84', '\x82', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x85', '\x3', '\x2', '\x2', '\x2', '\x85', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x84', '\x3', '\x2', '\x2', '\x2', '\x87', 
		'\x88', '\a', '$', '\x2', '\x2', '\x88', '(', '\x3', '\x2', '\x2', '\x2', 
		'\x89', '\x8B', '\t', '\x5', '\x2', '\x2', '\x8A', '\x89', '\x3', '\x2', 
		'\x2', '\x2', '\x8B', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8A', 
		'\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\x3', '\x2', '\x2', '\x2', 
		'\x8D', '*', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x90', '\t', '\x6', 
		'\x2', '\x2', '\x8F', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', 
		'\x3', '\x2', '\x2', '\x2', '\x91', '\x8F', '\x3', '\x2', '\x2', '\x2', 
		'\x91', '\x92', '\x3', '\x2', '\x2', '\x2', '\x92', ',', '\x3', '\x2', 
		'\x2', '\x2', '\xE', '\x2', 'O', 'T', '\x62', 'h', 'j', 'o', 'y', '\x82', 
		'\x84', '\x8C', '\x91', '\x4', '\b', '\x2', '\x2', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Sane.Grammar
